### ISSUE TITLE
Possible regression in 0b4fec1

### ISSUE THREAD

**Issue by djui** [nlf/dlite#105]
I upgraded dlite to master and now get an error when building using docker-compose:

```
:
docker-compose up --force-recreate
Removing project_db_1
Recreating fffad30f6a_fffad30f6a_fffad30f6a_fffad30f6a_fffad30f6a_fffad30f6a_fffad30f6a_project_db_1
ERROR: http: Hijack is incompatible with use of CloseNotifier
make: *** [up] Error 1
```

The interesting thing is the prefix that gets added every time I run docker-compose.

Going back to 1.3 resolves the issue. I am not sure how and if it ties into docker-compose.

**Comment by nlf** [comment]
does this happen for any compose file? or just a specific one? can you share your compose file, or a smaller one that reproduces this issue?

**Comment by nlf** [comment]
i just pushed a new commit, see if that works ok for you

**Comment by djui** [comment]
Thanks! I believe this solved the problem.

**Comment by djui** [comment]
Before closing the issue, two questions:

# Crashing image pulls

I now start to get a another problem, also related to docker-compose it seems, when initially pulling in a large amount of layers:

```
$ make up
docker-compose build
db uses an image, skipping
Building validator
Step 1 : FROM java
latest: Pulling from library/java
7268d8f794c4: Downloading [==============================>                    ] 30.85 MB/51.37 MB
a3ed95caeb02: Download complete
d9a49bc2b1b0: Download complete
b965864d2d45: Downloading [====================================>              ] 31.31 MB/42.49 MB
3c1db5f0dd6d: Download complete
5fe38b5ef80a: Download complete
f986c9558c3b: Download complete
dd5e772f0b5f: Waiting
bde56dd229ee: Waiting
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 55, in main
    command.sys_dispatch()
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 174, in perform_command
    handler(project, command_options)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 195, in build
    force_rm=bool(options.get('--force-rm', False)))
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/project.py", line 246, in build
    service.build(no_cache, pull, force_rm)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/service.py", line 682, in build
    all_events = stream_output(build_output, sys.stdout)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/progress_stream.py", line 18, in stream_output
    for event in utils.json_stream(output):
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/utils.py", line 63, in split_buffer
    yield decoder(buffered)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 3 column 1 - line 1524 column 1 (char 193 - 226683)
make: *** [all] Error 1
```

# Chunked docker output stream

This only happens the first time, when no docker images exist yet, but then quit consistently. The workaround is to just run it again and then it completes the process. Before this commit I was under the impression that this issue did not occur.

The second thing is that it seems docker operation got either slower or are perceived as to be slower, because the "screen update rate" in the terminal of output from Docker seems delayed until a certain output buffer is filled and then arrives in one junk. I believe this as well not to be the case before the commit. Every output "streamed" more fluently and similar to docker-machine. Is it just an illusion on my side?

**Comment by nlf** [comment]
the first issue i've also seen, and that's why i didn't close the issue yet. i _think_ what's happening is that the docker daemon is terminating the connection early and docker-compose is seeing some truncated output. i've done a little bit of debugging to determine why, but i don't have an answer yet. i'll keep working on that.

the second issue is likely exactly what you're thinking, a delay while a buffer fills. that should be tunable. i'll see what i can do.
