### ISSUE TITLE
Doesn't start on 10.11.4

### ISSUE THREAD

**Issue by Jellyfrog** [nlf/dlite#24]
Not sure if this is a dlite or xhyve problem

```
$ sudo dlite daemon
hv_vm_create failed
SIGABRT: abort
PC=0x7fff94af0f26 m=3
signal arrived during cgo execution

goroutine 6 [syscall, locked to thread]:
runtime.cgocall(0x42b0051, 0xc82003dbf0, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc82003dba8 sp=0xc82003db78
github.com/TheNewNormal/libxhyve._Cfunc_run_xhyve(0xc800000013, 0xc8200943c0, 0x0)
    github.com/TheNewNormal/libxhyve/_obj/_cgo_gotypes.go:92 +0x39 fp=0xc82003dbf0 sp=0xc82003dba8
github.com/TheNewNormal/libxhyve.Run(0xc82003de48, 0x13, 0x13, 0xc8200162a0, 0x0, 0x0)
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/src/github.com/TheNewNormal/libxhyve/xhyve.go:114 +0x1bf fp=0xc82003dce0 sp=0xc82003dbf0
github.com/nlf/dlite/utils.StartVM.func1(0xc820063320, 0x24, 0x1, 0x1, 0xc8200162a0, 0xc820016240)
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/src/github.com/nlf/dlite/utils/xhyve.go:27 +0x665 fp=0xc82003df80 sp=0xc82003dce0
runtime.goexit()
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82003df88 sp=0xc82003df80
created by github.com/nlf/dlite/utils.StartVM
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/src/github.com/nlf/dlite/utils/xhyve.go:29 +0xac

goroutine 1 [chan receive, locked to thread]:
github.com/nlf/dlite/utils.StartVM(0xc820063320, 0x24, 0x1, 0x1, 0x0)
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/src/github.com/nlf/dlite/utils/xhyve.go:31 +0xcf
main.(*DaemonCommand).Execute(0x47f5578, 0xc8200112b0, 0x0, 0x1, 0x0, 0x0)
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/daemon.go:21 +0xfe
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc82000e780, 0xc82000a0f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/src/github.com/jessevdk/go-flags/parser.go:301 +0xa16
github.com/jessevdk/go-flags.(*Parser).Parse(0xc82000e780, 0x0, 0x0, 0x0, 0x0, 0x0)
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/src/github.com/jessevdk/go-flags/parser.go:175 +0x9b
main.main()
    /private/tmp/dlite20160126-7701-1mi41uc/dlite-1.0.4/main.go:20 +0x3c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

rax    0x0
rbx    0x6
rcx    0x700000103ca8
rdx    0x0
rdi    0x1303
rsi    0x6
rbp    0x700000103cd0
rsp    0x700000103ca8
r8     0x40
r9     0x7fff75a671e0
r10    0x8000000
r11    0x206
r12    0x42d45c4
r13    0x0
r14    0x700000104000
r15    0x1
rip    0x7fff94af0f26
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

**Comment by nlf** [comment]
this is a xhyve problem, see https://github.com/mist64/xhyve/issues/83

**Comment by Jellyfrog** [comment]
Yeah I just saw it!
