### ISSUE TITLE
daemon won't start

### ISSUE THREAD

**Issue by caarlos0** [nlf/dlite#38]
I did:

```
brew install xhyve
```

Then download and put `dlite`binary in `/usr/local/bin/dlite`.

Then I ran:

```
sudo dlite install -d=10
launchctl load ~/Library/LaunchAgents/local.dlite.plist
```

Since nothing happened after that, I tried to launch the daemon using the binary, but it errored:

```
$ sudo dlite daemon
hv_vm_create failed
SIGABRT: abort
PC=0x7fff94429f26 m=4
signal arrived during cgo execution

goroutine 20 [syscall, locked to thread]:
runtime.cgocall(0x42afb81, 0xc820036bf0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc820036ba8 sp=0xc820036b78
github.com/TheNewNormal/libxhyve._Cfunc_run_xhyve(0xc800000013, 0xc8200ac3c0, 0x0)
    github.com/TheNewNormal/libxhyve/_obj/_cgo_gotypes.go:92 +0x39 fp=0xc820036bf0 sp=0xc820036ba8
github.com/TheNewNormal/libxhyve.Run(0xc820036e48, 0x13, 0x13, 0xc8200a0180, 0x0, 0x0)
    /Users/nathan/Go/src/github.com/TheNewNormal/libxhyve/xhyve.go:114 +0x1bf fp=0xc820036ce0 sp=0xc820036bf0
github.com/nlf/dlite/utils.StartVM.func1(0xc820067200, 0x24, 0x1, 0x1, 0xc8200a0180, 0xc8200a0120)
    /Users/nathan/Go/src/github.com/nlf/dlite/utils/xhyve.go:27 +0x665 fp=0xc820036f80 sp=0xc820036ce0
runtime.goexit()
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820036f88 sp=0xc820036f80
created by github.com/nlf/dlite/utils.StartVM
    /Users/nathan/Go/src/github.com/nlf/dlite/utils/xhyve.go:29 +0xac

goroutine 1 [chan receive, locked to thread]:
github.com/nlf/dlite/utils.StartVM(0xc820067200, 0x24, 0x1, 0x1, 0x0)
    /Users/nathan/Go/src/github.com/nlf/dlite/utils/xhyve.go:31 +0xcf
main.(*DaemonCommand).Execute(0x47f4578, 0xc8200631d0, 0x0, 0x1, 0x0, 0x0)
    /Users/nathan/Go/src/github.com/nlf/dlite/daemon.go:21 +0xfe
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc8200765a0, 0xc820074010, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/nathan/Go/src/github.com/jessevdk/go-flags/parser.go:301 +0xa16
github.com/jessevdk/go-flags.(*Parser).Parse(0xc8200765a0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/nathan/Go/src/github.com/jessevdk/go-flags/parser.go:175 +0x9b
main.main()
    /Users/nathan/Go/src/github.com/nlf/dlite/main.go:20 +0x3c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1

rax    0x0
rbx    0x6
rcx    0x700000186ca8
rdx    0x0
rdi    0x1503
rsi    0x6
rbp    0x700000186cd0
rsp    0x700000186ca8
r8     0x40
r9     0x7fff72ae91e0
r10    0x8000000
r11    0x206
r12    0x42d3ffc
r13    0x0
r14    0x700000187000
r15    0x1
rip    0x7fff94429f26
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

I'm using OS X 10.11.4 Beta (15E27e) and xhyve 0.2.0.

**Comment by caarlos0** [comment]
Just realized it is a xhyve problem: mist64/xhyve#83
